Complete first part.
Curiosity10/reactjs-films-homework pull request #1
Opened 2018-11-26 19:55 UTC by Curiosity10

Complete first part of reactjs-films-homework.

2018-11-28 13:10 UTC, EduardTrutsyk commented
не минифицированы скрипты на демо

2018-11-28 13:10 UTC, EduardTrutsyk requested changes

2018-11-28 13:10 UTC, EduardTrutsyk commented on frontend/build/index.html
> +<!DOCTYPE html>
не нужно комитать в репозиторий `build` папку, добавь ее в игнор, иначе в каждом Pull Request будут изменения в этих файлах

2018-11-28 13:10 UTC, EduardTrutsyk commented on frontend/config/webpack/webpack.prod.config.js
> +    new BrotliPlugin(),
для чего тебе этот плагин?

2018-11-28 13:10 UTC, EduardTrutsyk commented on frontend/src/components/Signature/Signature.jsx
> +  name: PropTypes.string,
это должен быть обязательный параметр

2018-11-28 13:10 UTC, EduardTrutsyk commented on frontend/src/components/Signature/__tests__/Signature.spec.js
> +renderer.render(<Signature />);
лучше такую логику писать в самом тесте, и тестироватьс с разными пропсами

2018-11-28 13:10 UTC, EduardTrutsyk commented on frontend/src/components/Signature/index.js
> +ReactDOM.render(<Signature name="Dzmitry Aleksandrouski" />, document.getElementById('app') || document.createElement('div'));
достаточно одного заранее известного рутового элемента

2018-11-28 13:10 UTC, EduardTrutsyk commented on package.json
> +    "prod": "concurrently \"webpack --config=frontend/config/webpack/webpack.prod.config.js\" \"set NODE_ENV=production && node ./index.js\"",
не нужно при запуске в прод режиме собирать проект, это должно делать один раз и для этго есть команда `npm build`

2018-11-28 13:12 UTC, EduardTrutsyk commented
у тебя есть другая папка кроме `frontend`? такие вещи как frontend и backend должны быть в разных репозиториях

2018-11-28 13:15 UTC, EduardTrutsyk commented on package.json
> +    "lint": "concurrently \"eslint --debug frontend/src/\" \"stylelint \"./frontend/src/**/*.scss\" --formatter verbose\"",
давай не будем использовать `concurrently`? ничего лишнего, все должно быть максимально просто.

2018-11-28 13:16 UTC, EduardTrutsyk commented
и следи за Travis-CI, билд должен быть всегда зеленый

2018-11-28 15:52 UTC, alexander-lozovsky requested changes

2018-11-28 15:52 UTC, alexander-lozovsky commented on .eslintignore
> +/.git
Тебе не нужна эта строчка

2018-11-28 15:52 UTC, alexander-lozovsky commented on .travis.yml
> +  - npm run lint
Добавь еще `npm test`

2018-11-28 15:52 UTC, alexander-lozovsky commented on frontend/src/components/Signature/index.js
> +import React from 'react';
Этот файл должен быть в `src/`

2018-11-28 15:52 UTC, alexander-lozovsky commented on index.js
> +const development = process.env.NODE_ENV !== 'production ';
1. Лишний пробел  в строке 'production '
2. Плохой нейминг. Должно быть что-то вроде `isDevelopmentEnv`
3. Лучше сделай что-то вроде `switch(process.env.NODE_ENV) {..`, так будет читабельнее.

2018-11-28 15:52 UTC, alexander-lozovsky commented on index.js
> +  const wpmw = webpackDevMiddleware(compiler, {
Лучше перемести эту логику в `app.use(`. В твоем случае эта переменная не повышает читабельности.
Вообще старайся избегать сокращений в именовании сущностей, то что тебе кажется очевидным не всегда является таковым для других. Читаемость как правило лучше лаконичности

2018-11-28 15:52 UTC, alexander-lozovsky commented on frontend/src/components/Signature/__tests__/Signature.spec.js
> +it('Test props', () => {
Ипользуй что-то одно, либо `test` либо `it`

2018-11-28 15:52 UTC, alexander-lozovsky commented on .stylelintrc
> +  "syntax": "scss",
Ты вроде как `sass` используешь

2018-11-28 15:52 UTC, alexander-lozovsky commented on package.json
> +    "lint": "concurrently \"eslint --debug frontend/src/\" \"stylelint \"./frontend/src/**/*.scss\" --formatter verbose\"",
Stylelint линтит `.scss` вместо `.sass`

2018-11-30 08:02 UTC, EduardTrutsyk commented on frontend/src/components/Signature/Signature.sass
> +.header
предлагаю использвать синтксис `scss`, что бы было максимально приближено к чистому css

2018-11-30 08:06 UTC, Curiosity10 commented on frontend/config/webpack/webpack.prod.config.js
> +    new BrotliPlugin(),
Ну он просто сжимает уже минифицированный js еще в 3 раза примерно, это как gzip, только чуть лучше. Просто чтобы добиться меньшего размера у конечного бандла, который принимает браузер, я и использую его. Вот размеры .js и .js.br:

2018-11-30 08:09 UTC, EduardTrutsyk commented on .stylelintrc
> +  "syntax": "scss",
но давайте использовать `scss`, я обновил требования.

2018-12-03 09:14 UTC, alexander-lozovsky approved these changes

2018-12-04 11:32 UTC, EduardTrutsyk approved these changes

2018-12-04 12:01 UTC, merged